use_frameworks!

platform :ios, '8.0'

target 'ACStatusHUD_Example' do
  pod 'SVProgressHUD'
  pod 'ACStatusHUD', :path => '../'

  target 'ACStatusHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
